mvn.ratio.tlr <- function(lower=-Inf, upper=Inf, mean=0, sigma=NULL, m = 64, epsl = 1e-3, N=499)
{
  # check geom and sigma
  if(is.null(sigma))
    stop("`sigma` should be given")
  n = nrow(sigma)
  if(ncol(sigma) != n)
    stop("Row number and column number of `Sigma` do not match")
  if(any(is.na(sigma)))
    stop("`sigma` contains NA")
  # check lower, upper, and mean
  if(n == 0)
    stop("Problem dimension cannot be zero")
  if(!is.numeric(lower) || !is.vector(lower))
    stop('`lower` should be numeric vector')
  if(!is.numeric(upper) || !is.vector(upper))
    stop('`upper` should be numeric vector')
  if(!is.numeric(mean) || !is.vector(mean))
    stop('`mean` should be numeric vector')
  if(length(lower) == 1)
    lower = rep(lower, n)
  if(length(lower) != n)
    stop('Length of `lower` does not match the problem dimension')
  if(length(upper) == 1)
    upper = rep(upper, n)
  if(length(upper) != n)
    stop('Length of `upper` does not match the problem dimension')
  if(length(mean) == 1)
    mean = rep(mean, n)
  if(length(mean) != n)
    stop('Length of `mean` does not match the problem dimension')
  if(any(is.na(lower)))
    stop("`lower` contains NA")
  if(any(is.na(upper)))
    stop("`upper` contains NA")
  if(any(is.na(mean)))
    stop("`mean` contains NA")
  # check N
  if(!is.numeric(N))
    stop("`N` should be numeric")
  if(is.na(N))
    stop("`N` cannot be NA")
  if(length(N) != 1)
    stop("`N` should be of length 1")
  if(N < 100)
    stop("Monte Carlo sample size `N` should be at least 100")
  # check m
  if(!is.numeric(m))
    stop("`m` should be numeric")
  if(is.na(m))
    stop("`m` cannot be NA")
  if(length(m) != 1)
    stop("`m` should be of length 1")
  if(m < 4)
    stop("Block size `m` should be at least 4")
  if(m >= n)
    stop("Block size `m` should be smaller than the problem dimension")
  # check epsl
  if(!is.numeric(epsl))
    stop("`epsl` should be numeric")
  if(is.na(epsl))
    stop("`epsl` cannot be NA")
  if(length(epsl) != 1)
    stop("`epsl` should be of length 1")
  if(epsl <= 0)
    stop("`epsl` should be greater than 0")
  # pass to the internal function
  lower <- lower - mean
  upper <- upper - mean
  if(any(lower > upper))
    stop("At least one `upper` coefficient is smaller than `lower`")
  tlrmvnratio_internal(lower, upper, sigma, m, epsl, N)
}
