# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tlrmvnratio_internal <- function(a, b, covM, m, epsl, N) {
    .Call('_tlrmvnratio_tlrmvnratio_internal', PACKAGE = 'tlrmvnratio', a, b, covM, m, epsl, N)
}

zorder <- function(geom) {
    .Call('_tlrmvnratio_zorder', PACKAGE = 'tlrmvnratio', geom)
}

